Revert "[swarming] update index to have dimensions_flat duplicated"
This reverts commit 1436a3579c5ecbadd7dfc9a28c0dcc87c78e37e1.

Reason for revert: Generates errors like:

BadRequestError: Index entries too large for entity: app: "s~(instance)",path < Element { type: "BotRoot", name: "(botid)" }, Element { type: "BotInfo", name: "info" }>

:(

Original change's description:
> [swarming] update index to have dimensions_flat duplicated
> 
> This should improve COUNT operation performance for the bots.count API when
> multiple dimensions are used, resulting in dimensions_flat to be specified
> multiple times.
> 
> More information at https://cloud.google.com/appengine/articles/indexselection
> 
> Manually sorted the entries.
> 
> Bug: 825843
> Change-Id: I74dde54ecaa307066f8748132a454579434d3ab7
> Reviewed-on: https://chromium-review.googlesource.com/980959
> Reviewed-by: Andrii Shyshkalov <tandrii@chromium.org>
> Commit-Queue: Marc-Antoine Ruel <maruel@chromium.org>

TBR=maruel@chromium.org,iannucci@chromium.org,nodir@chromium.org,tandrii@chromium.org

Change-Id: I6d7eb5d109c35e293435eca45c8918617e567eb0
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 825843
Reviewed-on: https://chromium-review.googlesource.com/981753
Reviewed-by: Marc-Antoine Ruel <maruel@chromium.org>
Commit-Queue: Marc-Antoine Ruel <maruel@chromium.org>