Revert of Bump python-libusb1 to 1.6 (patchset #1 id:1 of https://codereview.chromium.org/2591753004/ )
Reason for revert:
Breaks bot code

New bot code is bad: proc exit = 1. stdout:
Traceback (most recent call last):
File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
"__main__", fname, loader, pkg_name)
File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
exec code in run_globals
File "/b/swarm_slave/swarming_bot.2.zip/__main__.py", line 257, in <module>
File "/b/swarm_slave/swarming_bot.2.zip/__main__.py", line 245, in main
File "/b/swarm_slave/swarming_bot.2.zip/__main__.py", line 81, in CMDis_fine
File "/b/swarm_slave/swarming_bot.2.zip/bot_code/bot_main.py", line 42, in <module>
File "/b/swarm_slave/swarming_bot.2.zip/api/bot.py", line 11, in <module>
File "/b/swarm_slave/swarming_bot.2.zip/api/os_utilities.py", line 36, in <module>
File "/b/swarm_slave/swarming_bot.2.zip/api/platforms/__init__.py", line 31, in <module>
File "/b/swarm_slave/swarming_bot.2.zip/api/platforms/android.py", line 17, in <module>
File "/b/swarm_slave/swarming_bot.2.zip/adb/common.py", line 24, in <module>
File "/b/swarm_slave/swarming_bot.2.zip/python_libusb1/libusb1.py", line 8, in <module>
File "/b/swarm_slave/swarming_bot.2.zip/python_libusb1/usb1.py", line 83, in <module>
AttributeError: 'module' object has no attribute 'USBError'

Original issue's description:
> Bump python-libusb1 to 1.6
>
> R=bpastene@chromium.org
> BUG=
>
> Review-Url: https://codereview.chromium.org/2591753004
> Committed: https://github.com/luci/luci-py/commit/9e744e70b9a9a7622e1663447171c8b6b78f1cb0

TBR=maruel@chromium.org
# Not skipping CQ checks because original CL landed more than 1 days ago.
BUG=

Review-Url: https://codereview.chromium.org/2615563005