Fix ts_mon MP related exception
The exception looks like:
  MonitoringDecreasingValueError: Monotonically increasing metric
  "swarming/machine_types/connection_time" was given value "-646366.46372",
  which is not greater than or equal to "None".

This change does not fix the underlying issue but at least makes sure that when
this happens, the whole handler doesn't throw and result in an HTTP 500.

R=smut@chromium.org
BUG=

Review-Url: https://codereview.chromium.org/2907623003