swarming: Recognize 'Google Tamar' as a GCE cpu platform
"n4a" is one of the arm-based gen4 machine types for GCE:
https://docs.cloud.google.com/compute/docs/general-purpose-machines#n4a_series

Such instances are unable to run a swarming bot due to errors like:
   File "/b/s/swarming_bot.1.zip/api/platforms/gce.py", line 346, in get_cpuinfo_uncached
     assert cpu_name is not None, cpu_platform
            ^^^^^^^^^^^^^^^^^^^^
 AssertionError: Google Tamar

And its metadata has this field in it:
"cpuPlatform": "Google Tamar",

So we assume we just need to allowlist that platform in swarming's bot
code here.

Bug: 493612000
Change-Id: I21f70a34b74dae216004f9a6e1c00cf5ea3b04cf
Reviewed-on: https://chromium-review.googlesource.com/c/infra/luci/luci-py/+/7708539
Commit-Queue: Ben Pastene <bpastene@chromium.org>
Reviewed-by: Vadim Shtayura <vadimsh@chromium.org>