[luci-py] fix import error at local_smoke_test.py
./test.py at appengine/swarming fails at local_smoke_test.py.
"from tools import start_bot" can't find "start_bot" since it loads from "appengine/components/tools".
This CL solves the name conflict.

```
~/chrome_infra/infra/luci/appengine/swarming master* 9s
❯ ./test.py --exclude-plugin nose2.plugins.mp --fail-fast
E
======================================================================
ERROR: local_smoke_test (nose2.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: local_smoke_test
Traceback (most recent call last):
  File "/home/jwata/.vpython-root/24ef20/local/lib/python2.7/site-packages/nose2/plugins/loader/discovery.py", line 201, in _find_tests_in_file
    module = util.module_from_name(module_name)
  File "/home/jwata/.vpython-root/24ef20/local/lib/python2.7/site-packages/nose2/util.py", line 77, in module_from_name
    __import__(name)
  File "/home/jwata/chrome_infra/infra/luci/appengine/swarming/local_smoke_test.py", line 41, in <module>
    from tools import start_bot
ImportError: cannot import name start_bot


----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
```

Note that this error doesn't seem to always happen. (ordering issue)

Change-Id: I10b71d3f642048536f3ca65992146f6bdda524cb
Reviewed-on: https://chromium-review.googlesource.com/c/infra/luci/luci-py/+/2082293
Auto-Submit: Junji Watanabe <jwata@google.com>
Commit-Queue: Takuto Ikuta <tikuta@chromium.org>
Reviewed-by: Takuto Ikuta <tikuta@chromium.org>