[auth_service] Attempt to fix "ImportError: cannot import name ts_mon".
These errors started to appear randomly out of nowhere on GAE. They seem to be
related to protobuf. The very first error encountered by a process is
"ImportError: No module named protobuf", then it starts complaining "cannot
import name ts_mon", and eventually magically "succeeds".

The suspected cause is misconfigured protobuf path in 'gae_ts_mon' module.

R=tandrii@chromium.org, maruel@chromium.org

Change-Id: I3901156e7ccf680723428ad3ca271a44e2f42f45
Reviewed-on: https://chromium-review.googlesource.com/823139
Reviewed-by: Andrii Shyshkalov <tandrii@chromium.org>
Commit-Queue: Vadim Shtayura <vadimsh@chromium.org>