swarming_bot: fix exception in case of misconfiguration
I observed a Raspberry Pi misconfigured where libusb is not installed.
It failed with:

  File /.../swarming_bot.1.zip/api/platforms/android.py, line 118, in get_devices
    if not gce.is_gce():
NameError: global name 'gce' is not defined

This is because the gce import was in the try / except block instead of
after. This was the case since 3574a8419b1040e4da6a92fe376bc79b87d21d70 but it
was also broken before.

R=jchinlee@chromium.org

Change-Id: I76034ed48f0b17021d4a10228e9cdea12540114b
Reviewed-on: https://chromium-review.googlesource.com/c/infra/luci/luci-py/+/1647037
Reviewed-by: Jao-ke Chin-Lee <jchinlee@chromium.org>
Commit-Queue: Marc-Antoine Ruel <maruel@chromium.org>