Revert "[luci-py] fix import error at local_smoke_test.py"
This reverts commit 73469a1aaecea527837976c6eb8b4d5dadd62427.

Reason for revert: the directory name "tools" are widely used in other appengine projects.
https://source.chromium.org/search?q=f:appengine%20f:tools&sq=&originalUrl=https:%2F%2Fcs.chromium.org%2F

And some script like deploy.py hardcode 'tools' to find gae, gae.py etc.

Original change's description:
> [luci-py] fix import error at local_smoke_test.py
> 
> ./test.py at appengine/swarming fails at local_smoke_test.py.
> "from tools import start_bot" can't find "start_bot" since it loads from "appengine/components/tools".
> This CL solves the name conflict.
> 
> ```
> ~/chrome_infra/infra/luci/appengine/swarming master* 9s
> ❯ ./test.py --exclude-plugin nose2.plugins.mp --fail-fast
> E
> ======================================================================
> ERROR: local_smoke_test (nose2.loader.ModuleImportFailure)
> ----------------------------------------------------------------------
> ImportError: Failed to import test module: local_smoke_test
> Traceback (most recent call last):
>   File "/home/jwata/.vpython-root/24ef20/local/lib/python2.7/site-packages/nose2/plugins/loader/discovery.py", line 201, in _find_tests_in_file
>     module = util.module_from_name(module_name)
>   File "/home/jwata/.vpython-root/24ef20/local/lib/python2.7/site-packages/nose2/util.py", line 77, in module_from_name
>     __import__(name)
>   File "/home/jwata/chrome_infra/infra/luci/appengine/swarming/local_smoke_test.py", line 41, in <module>
>     from tools import start_bot
> ImportError: cannot import name start_bot
> 
> 
> ----------------------------------------------------------------------
> Ran 1 test in 0.000s
> 
> FAILED (errors=1)
> ```
> 
> Note that this error doesn't seem to always happen. (ordering issue)
> 
> Change-Id: I10b71d3f642048536f3ca65992146f6bdda524cb
> Reviewed-on: https://chromium-review.googlesource.com/c/infra/luci/luci-py/+/2082293
> Auto-Submit: Junji Watanabe <jwata@google.com>
> Commit-Queue: Takuto Ikuta <tikuta@chromium.org>
> Reviewed-by: Takuto Ikuta <tikuta@chromium.org>

TBR=tikuta@chromium.org,jwata@google.com,infra-scoped@luci-project-accounts.iam.gserviceaccount.com

# Not skipping CQ checks because original CL landed > 1 day ago.

Change-Id: I3e057d152b85b75471a8d511ffcfaca890c2d3dd
Reviewed-on: https://chromium-review.googlesource.com/c/infra/luci/luci-py/+/2084322
Reviewed-by: Junji Watanabe <jwata@google.com>
Reviewed-by: Takuto Ikuta <tikuta@chromium.org>
Commit-Queue: Junji Watanabe <jwata@google.com>
Auto-Submit: Junji Watanabe <jwata@google.com>