Fix exception due to str/unicode mismatch.
This would cause an exception of type:
(...)
  File components/ereporter2/logscraper.py, line 194, in __init__
    assert isinstance(self.signature, unicode), repr(self.signature)
AssertionError: 'Exceeded soft private memory limit'

TBR=vadimsh@chromium.org
BUG=

Review URL: https://codereview.appspot.com/155550043