[components] Fix "gae.py switch" error when switching from/to spinnaker version
"gae.py switch" fails with Spinnaker versions which doesn't include pseudo version number.

```
Traceback (most recent call last):
  File "/Users/jwata/chrome_infra_internal/infra/luci/appengine/components/tools/gae.py", line 545, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/Users/jwata/chrome_infra_internal/infra/luci/appengine/components/tools/gae.py", line 534, in main
    return dispatcher.execute(OptionParser(default_app_dir), args)
  File "/Users/jwata/chrome_infra_internal/infra/luci/appengine/components/../../client/third_party/depot_tools/subcommand.py", line 252, in execute
    return command(parser, args[1:])
  File "/Users/jwata/chrome_infra_internal/infra/luci/appengine/components/tools/gae.py", line 402, in CMDupload
    _print_version_log(app, version)
  File "/Users/jwata/chrome_infra_internal/infra/luci/appengine/components/tools/gae.py", line 70, in _print_version_log
    start = int(from_version.split('-', 1)[0])
ValueError: invalid literal for int() with base 10: 'swarming'
```

Bug: b/169716604
Change-Id: I5deedf748943a561244cb05d7b2cf0e2802f7b72
Reviewed-on: https://chromium-review.googlesource.com/c/infra/luci/luci-py/+/2580981
Commit-Queue: Vadim Shtayura <vadimsh@chromium.org>
Reviewed-by: Vadim Shtayura <vadimsh@chromium.org>
Auto-Submit: Junji Watanabe <jwata@google.com>