Revert "bot_code: use X-Luci-Swarming-Bot-ID header for bot_id"
This reverts commit 55e87f6be5e08d94a6bc2e9e876b03b948ef59d6.

Reason for revert: seems to cause
10967 2019-10-17 07:50:38.527 E: local_auth: Failed to grab access token from LUCI context server: "Internal error: mint_oauth_token() got an unexpected keyword argument 'bot_id'\n"

https://chromium-swarm-dev.appspot.com/task?d=true&id=47f183fa2cf35410&o=true

Original change's description:
> bot_code: use X-Luci-Swarming-Bot-ID header for bot_id
> 
> This derived from
> crrev.com/c/1862940/11/appengine/swarming/swarming_bot/bot_code/remote_client.py#343
> 
> Instead of passing bot_id to client, have bot_id in client and use that.
> 
> Bug: 1013451
> Change-Id: I79704e3e114fa82a77689ddb2a808a3211ca65db
> Reviewed-on: https://chromium-review.googlesource.com/c/infra/luci/luci-py/+/1866130
> Commit-Queue: Junji Watanabe <jwata@google.com>
> Auto-Submit: Takuto Ikuta <tikuta@chromium.org>
> Reviewed-by: Junji Watanabe <jwata@google.com>

TBR=yyanagisawa@google.com,tikuta@chromium.org,jwata@google.com

Change-Id: Idf7eb405c783a64fe78322db0fb8535a61a9f551
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 1013451
Reviewed-on: https://chromium-review.googlesource.com/c/infra/luci/luci-py/+/1866161
Reviewed-by: Takuto Ikuta <tikuta@chromium.org>
Commit-Queue: Takuto Ikuta <tikuta@chromium.org>