TaskResultSummary.duration can be None in case of internal failure.
Error generated internally is:
MonitoringDecreasingValueError: Monotonically increasing metric "jobs/durations"
was given value "None", which is not greater than or equal to "None".

Diagnosed via logs.

R=sergeyberezin@chromium.org
BUG=

Review-Url: https://codereview.chromium.org/2144733009