swarming_bot: fix a crash when upgrading very old bots.
This caused a crash like:
  File "/bot/swarming_bot.1.zip/api/os_utilities.py", line 628, in get_isolated_cache_info
    return dict(json.load(f)['items'])
  TypeError: list indices must be integers, not str

This causes the bot to quarantine, which is unneeded.

R=tandrii@chromium.org
Bug:
Change-Id: I514aa80f4b0f2c7ad17e25760e7088fa44114acd
Reviewed-on: https://chromium-review.googlesource.com/723480
Reviewed-by: Andrii Shyshkalov <tandrii@chromium.org>
Commit-Queue: Marc-Antoine Ruel <maruel@chromium.org>