Revert of Swarming: shard ts_mon metrics dynamically. (patchset #2 id:20001 of https://codereview.chromium.org/2461153002/ )
Reason for revert:
TypeError: datetime.datetime(2016, 10, 31, 23, 54, 10, 157080) is not JSON serializable

Original issue's description:
> Swarming: shard ts_mon metrics dynamically.
>
> BUG=657097
> R=maruel@chromium.org
>
> Committed: https://github.com/luci/luci-py/commit/efbb6d9f44d6a9f102e2844423fff97daf213056

TBR=maruel@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=657097

Review-Url: https://codereview.chromium.org/2469603002