[components] ignore no active version in gae.py
gae.py switch fails when "gcloud app versions list --hide-no-traffic" returns nothing.
This CL ignores the issue because the active version is used only for printing version log.

```
Traceback (most recent call last):
  File "./tools/gae", line 541, in <module>
    sys.exit(main(sys.argv[1:]))
  File "./tools/gae", line 530, in main
    return dispatcher.execute(OptionParser(default_app_dir), args)
  File "/usr/local/google/home/jwata/chrome_infra_internal/infra/luci/appengine/components/../../client/third_party/depot_tools/subcommand.py", line 252, in execute
    return command(parser, args[1:])
  File "./tools/gae", line 398, in CMDupload
    _print_version_log(app, version)
  File "./tools/gae", line 66, in _print_version_log
    start = int(from_version.split('-', 1)[0])
AttributeError: 'NoneType' object has no attribute 'split'
```

Change-Id: If1003bb97ed01520a179f4a12a5796785146e3da
Reviewed-on: https://chromium-review.googlesource.com/c/infra/luci/luci-py/+/2215521
Commit-Queue: Takuto Ikuta <tikuta@chromium.org>
Reviewed-by: Takuto Ikuta <tikuta@chromium.org>
Auto-Submit: Junji Watanabe <jwata@google.com>