Revert "[swarming-ui] setup eslint"
This reverts commit bd905cdcdb5eb3c5e26ce125510be7932d5d14c7.

Reason for revert: It fails to compile.

```
ERROR in ./modules/swarming-index/swarming-index.js
Module build failed (from ./node_modules/html-template-minifier-webpack/loader.js):
RangeError: Invalid string length
    at minifyTemplate (/Users/jwata/chrome_infra_internal/infra/luci/appengine/swarming/ui2/node_modules/html-template-minifier-webpack/loader.js:72:17)
    at Object.minifyHTMLInTemplates (/Users/jwata/chrome_infra_internal/infra/luci/appengine/swarming/ui2/node_modules/html-template-minifier-webpack/loader.js:31:17)
 @ ./modules/swarming-index/index.js 1:0-28
 @ ./pages/public_swarming_index.js
```

Original change's description:
> [swarming-ui] setup eslint
> 
> This is to improve code style under swarming/ui2.
> 
> Bug: 1099108
> Change-Id: Ifaa73a28120230a70c3ead30c986ebd75079c90a
> Reviewed-on: https://chromium-review.googlesource.com/c/infra/luci/luci-py/+/2265617
> Commit-Queue: Takuto Ikuta <tikuta@chromium.org>
> Reviewed-by: Takuto Ikuta <tikuta@chromium.org>
> Auto-Submit: Junji Watanabe <jwata@google.com>

TBR=tikuta@chromium.org,jwata@google.com,infra-scoped@luci-project-accounts.iam.gserviceaccount.com

Change-Id: I8387751ce0d66ba3d8d5ffafbff5ad5bc435b50b
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 1099108
Reviewed-on: https://chromium-review.googlesource.com/c/infra/luci/luci-py/+/2265622
Reviewed-by: Junji Watanabe <jwata@google.com>
Commit-Queue: Junji Watanabe <jwata@google.com>